apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: microservices

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "root123"

  MYSQL_DATABASE: "inventory"

  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "app123"

  REPLICATION_USER: "replicator"
  REPLICATION_PASSWORD: "replica123"

  MYSQL_EXPORTER_USER: "mysqlexporter"
  MYSQL_EXPORTER_PASSWORD: "exporter123"
