apiVersion: v1
kind: Service

metadata:
  name: frontend-preview
  namespace: microservices

  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: microservices-platform

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: frontend

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
