apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: microservices-alerts
  namespace: monitoring
spec:
  route:
    receiver: telegram
    groupBy:
      - alertname
      - service
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: alertname
        value: BackendRolloutFailed
        matchType: "="

  receivers:
    - name: telegram
      telegramConfigs:
        - sendResolved: true

          botToken:
            name: alertmanager-telegram
            key: bot-token

          chatID: 8899077998

          parseMode: HTML

          message: |
            {{ if eq .Status "firing" }}
            <b>🚨 Backend Rollout Failed</b>
            {{ else }}
            <b>✅ Backend Rollout Recovered</b>
            {{ end }}

            <b>Alert:</b> {{ .CommonLabels.alertname }}
            <b>Service:</b> {{ .CommonLabels.service }}
            <b>Severity:</b> {{ .CommonLabels.severity }}

            <b>Summary:</b>
            {{ .CommonAnnotations.summary }}

            <b>Description:</b>
            {{ .CommonAnnotations.description }}
