apiVersion: v1
kind: Service
metadata:
  name: mysql-write
  namespace: microservices
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: write-service
    app.kubernetes.io/part-of: microservices-platform
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app.kubernetes.io/name: mysql
    mysql-role: primary
