apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: backend
  namespace: microservices
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: microservices-platform

spec:
  replicas: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: backend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: microservices-platform

    spec:
      containers:
        - name: backend
          image: a7medsayed/backend:v1.0.2
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 4000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 384Mi

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false

  strategy:
    canary:
      stableService: backend-stable
      canaryService: backend-canary

      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: application-route
            namespace: microservices

      steps:
        - setWeight: 10
        - analysis:
            templates:
              - templateName: backend-availability
        - pause: {}

        - setWeight: 25
        - analysis:
            templates:
              - templateName: backend-availability
        - pause: {}

        - setWeight: 50
        - analysis:
            templates:
              - templateName: backend-availability
        - pause: {}

        - setWeight: 100
