apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  namespace: microservices
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: microservices-platform
    monitoring: backend-canary
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
  type: ClusterIP
