apiVersion: v1
kind: Service

metadata:
  name: mysql-primary
  namespace: microservices

  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: primary
    app.kubernetes.io/part-of: microservices-platform

spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: primary

  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
