apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-primary-data
  namespace: microservices

  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: primary
    app.kubernetes.io/part-of: microservices-platform

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: longhorn

  resources:
    requests:
      storage: 10Gi
