apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-gateway-workers
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          nodeSelector:
            node-role.kubernetes.io/worker: "true"
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: eg-gateway
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
        replicas: 3

      envoyService:
        externalTrafficPolicy: Cluster
