apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: microservices-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:ahmed-sayed-devops/microservices-platform-gitops.git
    targetRevision: main
    path: apps

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc

  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[].backendRefs[].weight

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
