apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-canary
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - microservices
  selector:
    matchLabels:
      monitoring: backend-canary
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
